### ISSUE TITLE
Hello?

### ISSUE THREAD

**Issue by matthew4444** [UniversMakers/EnderAuth#1]
u on netherowner?

**Comment by NetherOwner** [comment]
Yes

**Comment by matthew4444** [comment]
guess wht

**Comment by matthew4444** [comment]
rembember tht book i said ill give u a templete as text and u can make an epic front and back cover, u hear me?

**Comment by NetherOwner** [comment]
Yes

**Comment by matthew4444** [comment]
kk

**Comment by matthew4444** [comment]
brb im making cover for u to edit,it might be a while

**Comment by NetherOwner** [comment]
Whats with that

**Comment by NetherOwner** [comment]
Okau

**Comment by matthew4444** [comment]
brb

**Comment by matthew4444** [comment]
The Book Of PocketMine!
PMMP LOGO
A Guide On What We Plugin Developers Do, And The World's First Guide To Code PocketMine, With In Depth Coding, And Tourtials About Starting With Using IDE's, And NotePad++, And Real World Examples From Our Development Team.

**Comment by matthew4444** [comment]
front cover ^
                     |

**Comment by NetherOwner** [comment]
Cool/nice

**Comment by matthew4444** [comment]
can u make a great cover from it

**Comment by matthew4444** [comment]
can u make a great cover from it

**Comment by matthew4444** [comment]
can u make a great cover from The Book Of PocketMine!
PMMP LOGO
A Guide On What We Plugin Developers Do, And The World's First Guide To Code PocketMine, With In Depth Coding, And Tourtials About Starting With Using IDE's, And NotePad++, And Real World Examples From Our Development Team. @NetherOwner

**Comment by matthew4444** [comment]
?

**Comment by NetherOwner** [comment]
Uhh you what you mean exacly can you not say make a front and put our logo on it?

**Comment by NetherOwner** [comment]
And can you talk on gitter pls

**Comment by matthew4444** [comment]
put our logo on it then,and ok

**Comment by matthew4444** [comment]
what giiter site

**Comment by matthew4444** [comment]
which gitter site

**Comment by NetherOwner** [comment]
Wait i am making a one and its gitter.im

**Comment by matthew4444** [comment]
url plz

**Comment by NetherOwner** [comment]
Kk wait

**Comment by matthew4444** [comment]
kk

**Comment by matthew4444** [comment]
u making book cover and gitter url?

**Comment by matthew4444** [comment]
i see it

**Comment by NetherOwner** [comment]
K
